# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{uat_director}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ben Askins"]
  s.date = %q{2010-06-07}
  s.description = %q{Adds a toolbar to your rails app that directs your clients to test stories that have been marked as 'delivered' in Pivotal Tracker }
  s.email = %q{ben.askins@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/uat_director.rb",
     "lib/uat_director/configuration.rb",
     "lib/uat_director/helpers.rb",
     "lib/uat_director/rack_app.rb",
     "lib/uat_director/templates/index.haml",
     "uat_director.gemspec"
  ]
  s.homepage = %q{http://github.com/benaskins/uat_director}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Direct your clients to test delivered features}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<pivotal-tracker>, [">= 0.1.3"])
      s.add_runtime_dependency(%q<haml>, [">= 3.0.9"])
      s.add_runtime_dependency(%q<rack>, [">= 1.1.0"])
    else
      s.add_dependency(%q<pivotal-tracker>, [">= 0.1.3"])
      s.add_dependency(%q<haml>, [">= 3.0.9"])
      s.add_dependency(%q<rack>, [">= 1.1.0"])
    end
  else
    s.add_dependency(%q<pivotal-tracker>, [">= 0.1.3"])
    s.add_dependency(%q<haml>, [">= 3.0.9"])
    s.add_dependency(%q<rack>, [">= 1.1.0"])
  end
end

